name = "llm-report-worker"
main = "src/index.ts"
compatibility_date = "2023-05-02"
usage_model = "unbound"
env = { }
node_compat = true

[triggers]
crons = [ ]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "8ebc6b14da5d4d2194bb59e98d76d386"
localConnectionString = "postgres://postgres:postgres@localhost:5432/llm_report?schema=public"